name: CI Validate

on:
  pull_request:
    branches: ['main', 'develop', 'release/*' ]

jobs:
  
  validate-code:
    name: Validate Code
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5 

      - name: Validate HTML/CSS
        run: |
          echo "Executando validação estrutural do Dashboard..."
